[package]
name = "sarekt"
version = "0.1.0"
authors = ["Brandon Pollack <brandonpollack23@gmail.com>"]
edition = "2018"

[[example]]
name = "00_base_code"
path = "examples/00_base_code.rs"

[[example]]
name = "01_init_instance"
path = "examples/01_init_instance.rs"

[dependencies]
ash = {git = "https://github.com/MaikKlein/ash" }
ash-window = {git = "https://github.com/brandonpollack23/ash-window" }
lazy_static = "^1.4.0"
log = "^0.4.8"
memoffset = "0.5.3"
nalgebra = "^0.20.0"
raw-window-handle = "^0.3.3"
slotmap = "^0.4.0"
static_assertions = "^1.1.0"
vk-shader-macros = "^0.2.2"
winit = "^0.21.0"

[dev-dependencies]
simple_logger = "^1.5.0"
